### PR TITLE
Trim input before scanning

### PR DESCRIPTION
**Pull request by drew-gross**
The tests say the scanner should generate an `Invalid` token, but I don't see why they should do that. Esp. for plugins, they shouldn't care that the input had whitespace.

Tagging @shockone because this is a change to tested behaviour so I would appreciate a second set of eyes.

### CODE REVIEW

**Comment by shockone** [comment]
The point was to have a parse tree isomorphic to the input string. With thins change if I parse three spaces I can't serialize it back to three spaces.

**Comment by shockone** [comment]
Does it cause some issues, @drew-gross?

**Comment by drew-gross** [comment]
Ah I see. For the plugins I'm writing I want to match against the parsed line to see if the command is applicable. Eg. for the `git branch` plugin I check if the parsed command line equals `[Word("git"), Word("branch")]`. But I also want the plugin to activate when the command line contains `"   git    branch   "`, so I made this change to ensure that `"git branch"` and `"    git    branch   "` parse to the same thing.

If the parse tree being isomorphic is important, I could come up with a different strategy.

**Comment by vshatskyi** [comment]
@drew-gross should we close this? Also, I believe that currently the examples you mentioned do get parsed to the same thing, it's a string containing only spaces that differs.

**Comment by drew-gross** [comment]
No, `"git branch "` definitely gets parsed to `[Word, Word, Invalid]` before this PR. I can update this PR to pass a modified parse tree to the plugins.

**Comment by vshatskyi** [comment]
Oh, that doesn't sound right. Perhaps the right solution would be for a node to "eat" all the preceding *and* the following spaces instead of only the former ones.

**Comment by drew-gross** [comment]
That seems like a good idea actually. I'll do that one.

**Comment by vshatskyi** [comment]
One more thing: please check where `LeafNode.spaces()` is used, and change the logic there to use spaces from both ends. Probably we can rename this one to `precedingSpaces` and name the new method `followingSpaces`.

**Comment by vshatskyi** [comment]
Oh, and `fullEnd` should be changed as well.

**Comment by drew-gross** [comment]
@vshatskyi I added the `followingSpaces`/`preceedingSpaces` like you suggested but I'm not sure what should be changed about `fullEnd`.

**Comment by vshatskyi** [comment]
You're right, it shouldn't be changed. Sorry about that.

**Comment by vshatskyi** [comment]
@drew-gross it seems that `followoingSpaces` broke autocompletion after a space. Try typing `git `. Previously it'd show the next token suggestions.

**Comment by drew-gross** [comment]
Whoops sorry :( I created a new issue.

**Pull request merged**
